### ISSUE TITLE
super tiny first-run issue

### ISSUE THREAD

**Issue by Asatas** [sahaisaumya/informal_fallacies#1]
Hi, I am currently attempting to reproduce your work for a task in a course at University of Zurich.
https://github.com/sahaisaumya/informal_fallacies/blob/630d56edb27fb0d5f32dd125ad6e886e4ca2955e/code/config.py#L34
-> local_files_only requires the BERT model to already be present in the environment and throws an error if it is not.

**Comment by sahaisaumya** [comment]
Yes, this needs to have non-finetuned BERT present.

By disabling `local_files_only` you can prompt it to download. Please [consult the documentation](https://huggingface.co/docs/transformers/v4.18.0/en/main_classes/model#transformers.PreTrainedModel.from_pretrained) to know more about the arguments.
