### ISSUE TITLE
Torch save path issue

### ISSUE THREAD

**Issue by Asatas** [sahaisaumya/informal_fallacies#2]
https://github.com/sahaisaumya/informal_fallacies/blob/630d56edb27fb0d5f32dd125ad6e886e4ca2955e/code/train.py#L92

This line requires the save path to already exist if --folder is nested
Solution 1: Check if the model path exists, otherwise create it.
Solution 2: Remove slashes from the save path

**Comment by sahaisaumya** [comment]
This is a minor check, just use [Path.mkdir](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir) from pathlib (or similar) library to check for, and create nested path if needed.
